{% set version = "0.11.0" %}
{% set hash_val = "2d49565e5eaacbee0be753fbfd1aab37" %}

package:
  name: librosa
  version: {{ version }}

source:
  fn: librosa-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/l/librosa/librosa-{{ version }}.tar.gz
  md5: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=48
    - wheel >=0.29.0

  run:
    - python >={{ python_min }}
    - audioread >=2.1.9
    - numpy >=1.22.3
    - scipy >=1.6.0
    - scikit-learn >=1.1.0
    - joblib >=1.0
    - matplotlib-base >=3.5.0
    - decorator >=4.3.0
    - numba >=0.51.0
    - pysoundfile >=0.12.1
    - pooch >=1.1
    - packaging >=20.0
    - soxr-python >=0.3.2
    - lazy_loader >=0.1
    - msgpack-python >=1.0
    - typing_extensions >=4.1.1
    - standard-aifc  # [py>=3.13]
    - standard-sunau  # [py>=3.13]

test:
  requires:
    - python {{ python_min }}
  imports:
    - librosa
    - librosa.core
    - librosa.feature
    - librosa.util
    - librosa.display

about:
  home: http://github.com/librosa/librosa
  license: ISC
  summary: Python module for audio and music processing

extra:
  recipe-maintainers:
    - bmcfee
