{% set version = "0.6.3" %}
{% set hash_type = "md5" %}
{% set hash_val = "4c34bab5d199384b491ca0b8573bc881" %}

package:
  name: librosa
  version: {{ version }}

source:
  fn: librosa-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/librosa/librosa-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools  # necessary for pkg_resources
    - audioread >=2.0.0
    - numpy >=1.8.0
    - scipy >=0.14.0
    - scikit-learn >=0.14.0,!=0.19.0
    - matplotlib >=1.5.0
    - joblib >=0.12.0
    - decorator >=3.0.0
    - six >=1.3
    - resampy >=0.2.0
    - numba >=0.38.0

test:
  imports:
    - librosa
    - librosa.core
    - librosa.feature
    - librosa.util
    - librosa.display

about:
  home: http://github.com/librosa/librosa
  license: ISC
  summary: 'Python module for audio and music processing'

extra:
  recipe-maintainers:
    - bmcfee
