{% set version = "0.10.0rc1" %}
{% set hash_val = "46adde5777822901d50f5706a0604029" %}

package:
  name: librosa
  version: {{ version }}

source:
  fn: librosa-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/librosa/librosa-{{ version }}.tar.gz
  md5: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=48
    - wheel >=0.29.0

  run:
    - python >=3.7
    - audioread >=2.1.9
    - numpy >=1.20.3
    - scipy >=1.2.0
    - scikit-learn >=0.20.0
    - joblib >=0.14.0
    - matplotlib-base >=3.3.0
    - decorator >=4.3.0
    - numba >=0.51.0
    - pysoundfile >=0.12.1
    - pooch >=1.0
    - packaging >=20.0
    - soxr-python >=0.3.2
    - lazy_loader >=0.1
    - msgpack-python >=1.0

test:
  imports:
    - librosa
    - librosa.core
    - librosa.feature
    - librosa.util
    - librosa.display

about:
  home: http://github.com/librosa/librosa
  license: ISC
  summary: Python module for audio and music processing

extra:
  recipe-maintainers:
    - bmcfee
