{% set version = "0.10.2.post1" %}
{% set hash_val = "363ea06f0ab197842fdfbc3e5d2d5462" %}

package:
  name: librosa
  version: {{ version }}

source:
  fn: librosa-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/l/librosa/librosa-{{ version }}.tar.gz
  md5: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=48
    - wheel >=0.29.0

  run:
    - python >={{ python_min }}
    - audioread >=2.1.9
    - numpy >=1.20.3, !=1.22.0, !=1.22.1, !=1.22.2
    - scipy >=1.2.0
    - scikit-learn >=0.20.0
    - joblib >=0.14.0
    - matplotlib-base >=3.5.0
    - decorator >=4.3.0
    - numba >=0.51.0
    - pysoundfile >=0.12.1
    - pooch >=1.1
    - packaging >=20.0
    - soxr-python >=0.3.2
    - lazy_loader >=0.1
    - msgpack-python >=1.0
    - typing_extensions >=4.1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - librosa
    - librosa.core
    - librosa.feature
    - librosa.util
    - librosa.display

about:
  home: http://github.com/librosa/librosa
  license: ISC
  summary: Python module for audio and music processing

extra:
  recipe-maintainers:
    - bmcfee
